### ISSUE TITLE
Porblèmes avec facebook

### ISSUE THREAD

**Issue by ndelavergne** [covoiturage-libre/covoiturage-libre#100]
### Comportement actuel
il y a un certain nombre de pb.
circular redirection ?
image > 8 Mo, je ne comprends pas

http://screencast.com/t/pKHFZuOZGh

détails ici 
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fcovoiturage-libre.fr%2F

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by thb** [comment]
On en est où avec les pb facebook ?

**Comment by AlexBillbao** [comment]
Ca serait super de pouvoir avoir une nouvelle miniature de partage pour le jour de l'an, car celle du joyeux Noel est d'hors et dejà périmée !!  Si d'ici 2 jours on pouvait partager le lien avec l'image concue par Nico (2017 année du covoiturage-libre) ca serait top !

**Comment by thb** [comment]
Plus de problème a priori.

J'ai mis à jour l'image de partage.
