### ISSUE TITLE
Problèmes d'accent

### ISSUE THREAD

**Issue by ndelavergne** [covoiturage-libre/covoiturage-libre#101]
### Comportement actuel
dans une liste de résultats http://screencast.com/t/zFk3khv86
dans une annonce http://screencast.com/t/dZbdmMsB
dans les commentaires http://screencast.com/t/XiGQ4O168HUI

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by AlexBillbao** [comment]
Ca ne concerne que les trajets sujets à migration si j'ai bien suivi la discussion FB ? Si oui c'en est bientot fini !!
