### ISSUE TITLE
ordre des suggestions géographiques

### ISSUE THREAD

**Issue by ndelavergne** [covoiturage-libre/covoiturage-libre#104]
### Comportement actuel
Romain : Sur le site covoiturage-libre.fr lorsque je fais une recherche ville départ ou arrivée Brest on me propose en premier résultat une ville d'Allemagne ça serait cool si on pouvait afficher en premier les villes Françaises.
![15672702_10211608918164015_2316556934335860710_n](https://cloud.githubusercontent.com/assets/23027156/21482210/2600ffaa-cb71-11e6-8ca7-6c65929dde6d.jpg)

Remarque complémetaire
Remarque de Matthieu Hubert : Petite suggestion sur la nouvelle interface : si on tape "Paris" en entier dans un champ de recherche, la première suggestion qui apparait est "Parisot", c'est pas très "ergonomique". Suggestion : la première proposition pourrait être dans les villes les plus recherchées statistiquement, ou les trajets les plus proposés. 
et com d'Alex : Thomas avait parlé d un systeme qui fait remonter les villes les plus recherchées. Est il en place pour se nourrir des recherches des usagers ?

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by AlexBillbao** [comment]
Idem pour 
BEAUVAIS  STRASBOURG MULHOUSE SELESTAT BESANCON
Les suggestions sortent des villes qui ne contiennent meme pas les lettres déja tapées ...  Ca a pas l'air évident à controler tout ca COURAGE !!

TOUJOURS DONNER PRIORITE AUX VILLES FRANCAISES SI POSSIBLE.
![capture d ecran 2016-12-28 a 03 15 54](https://cloud.githubusercontent.com/assets/24801105/21512312/403af93e-ccac-11e6-84e9-502b60bded53.png)
![capture d ecran 2016-12-28 a 03 16 24](https://cloud.githubusercontent.com/assets/24801105/21512310/40384d60-ccac-11e6-9d3c-89b653f40a29.png)
![capture d ecran 2016-12-28 a 03 16 53](https://cloud.githubusercontent.com/assets/24801105/21512311/403a3760-ccac-11e6-9b9f-705d18f923d6.png)
![capture d ecran 2016-12-28 a 03 17 24](https://cloud.githubusercontent.com/assets/24801105/21512313/403da6fc-ccac-11e6-8564-569a923e9b91.png)
![capture d ecran 2016-12-28 a 03 15 17](https://cloud.githubusercontent.com/assets/24801105/21512316/4686a31a-ccac-11e6-9732-8a27dfa2f53c.png)

**Comment by ndelavergne** [comment]
C'est ok pour moi
