### ISSUE TITLE
bloquer l'âge du conducteur à deux chiffres

### ISSUE THREAD

**Issue by ndelavergne** [covoiturage-libre/covoiturage-libre#112]
### Comportement actuel
pas de limites

### Comportement attendu
blocquer l'âge à des valeurs à 2 chiffres (Axel)

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by AlexBillbao** [comment]
Oui peu de chances d'avoir des conducteurs centenaires et ca évitera les blagues ... Enfin c est une modif qui n'aura qu'une valeur temporaire si il est prévu de créer des comptes. À ce stade final, sur les comptes il faudra aussi limiter l'age à des données "crédibles" ! DOnc oui, 2 chiffres me semble englober 100 pour cent de l'age de tout covoitureur !!

**Comment by Poussinou** [comment]
On pourrait voir un passager de plus de 100 éventuellement, même si la probabilité tend vers 0. Pourquoi ne pas plutôt imposer un âge inférieur à 120 par exemple, où qqc de ce genre? :)
