### ISSUE TITLE
bloc "libre" sur la home

### ISSUE THREAD

**Issue by ndelavergne** [covoiturage-libre/covoiturage-libre#121]
### Comportement actuel
sur chrome j'ai encore des petits signes bizarres
http://screencast.com/t/qly0xdaxIa

### Comportement attendu
à supprimer, non ?

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by MickaelC87** [comment]
Visibles chez moi aussi, sur Chrome aussi.

**Comment by thb** [comment]
Et maintenant, vous l'avez encore ?

**Comment by MickaelC87** [comment]
Chez moi je les vois encore.

**Comment by didierClin** [comment]
Bjr,
ce comportement n'est visible que sur chrome en environnement  windows. 
Je ne l'observe pas sous linux.
une piste: https://bugs.chromium.org/p/chromium/issues/detail?id=550275

**Comment by Poussinou** [comment]
Pareil que DidierClin, je ne l'observe pas sous firefox pour linux

**Comment by Poussinou** [comment]
Normalement résolu par la PR citée plus haut
