### ISSUE TITLE
formulaire de recherche: créer un bouton switch pour intervertir "on click" les valeurs des champs départ et arrivée.

### ISSUE THREAD

**Issue by thb** [covoiturage-libre/covoiturage-libre#129]
### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by AlexBillbao** [comment]
évolution très attendue. Demandée par quelqu'un sur la hotline aussi.

**Comment by nicolasleger** [comment]
@thb @AlexBillbao @Poussinou Je viens de proposer une PR pour cet ajout => https://github.com/covoiturage-libre/covoiturage-libre/pull/170

**Comment by Poussinou** [comment]
@nicolasleger Super, ton travail est impressionnant, le site s'améliore vraiment grâce à toi. :) Je devrai récupérer des logins et des tas de trucs dans les deux semaines qui viennent, on va doucement pouvoir commencer à déployer les nouveautés :) Je voudrai te parler un peu en privé si ça te dérange pas, rejoins le groupe https://www.facebook.com/groups/covoiturage.libre.test/ sur facebook, je te retrouverai ensuite. Merci encore pour ton travail !

**Comment by nicolasleger** [comment]
@Poussinou Pas de soucis, j'ai déjà intégré le groupe ( cherches Nico du 15 Avril ).

**Comment by AlexBillbao** [comment]
Elle a été pushée sur le site test la PR de Nico sur ce point ?

**Comment by webplate** [comment]
Oui mais ici https://github.com/covoiturage-libre/covoiturage-libre/pull/203

**Comment by webplate** [comment]
It can be tested usually on https://covoli-dev.scalingo.io/

Unfortunately Scalingo disables the dev app at random. Contact me to try to push it back online.

**Comment by webplate** [comment]
Intégré à la branche master. Je ferme.
