### ISSUE TITLE
Trajet s'affichant deux fois dans une recherche

### ISSUE THREAD

**Issue by ndelavergne** [covoiturage-libre/covoiturage-libre#139]
Sur une requête Paris>Bordeaux, un trajet s'affiche deux fois
https://www.screencast.com/t/QducmKeBcRD
Pourquoi ?

**Comment by AlexBillbao** [comment]
Ce cas arrive très souvent.

Parfois c'est pour le meme trajet, parfois il apparait 2 fois car 2 des villes étapes sont ds le rayon de 25 km.

**Comment by nicolasleger** [comment]
En effet cela vient de la requête SQL effectuée pour rechercher les points d'un trajet, si un trajet en possède plusieurs qui satisfont la condition.

Pour déboguer :

```
city = City.create!

Trip.create!(
  departure_date: Date.today,
  departure_time: Time.now,
  price: 12,
  title: 'M',
  name: 'John',
  email: 'yolo@example.com',
  seats: 2,
  comfort: 'comfort',

  points: [
    Point.new(kind: 'From', lat: 23, lon: 24, city: city),
    Point.new(kind: 'Step', lat: 24, lon: 25, city: city, rank: 1, price: 4),
    Point.new(kind: 'Step', lat: 25, lon: 26, city: city, rank: 2, price: 5),
    Point.new(kind: 'To', lat: 83, lon: 84, city: city)
  ]
)


# 1) point_b_id (actual)
Trip.unscoped.includes(:points).select('trips.*, point_b.id as point_b_id, trips.id').
joins('INNER JOIN points AS point_b ON trips.id = point_b.trip_id').
where("point_b.kind <> 'From'").page(1).per(10).map(&:id)
# => [5, 5, 5]

# 2) DISTINCT only
Trip.unscoped.includes(:points).select('DISTINCT trips.id, trips.*').
joins('INNER JOIN points AS point_b ON trips.id = point_b.trip_id').
where("point_b.kind <> 'From'").page(1).per(10).map(&:id)
# => [5]

# 3) DISTINCT + point_b_id
Trip.unscoped.includes(:points).select('DISTINCT trips.id, trips.*, point_b.id as point_b_id').
joins('INNER JOIN points AS point_b ON trips.id = point_b.trip_id').
where("point_b.kind <> 'From'").page(1).per(10).map(&:id)
# => [5, 5, 5]
```

**Comment by nicolasleger** [comment]
Une solution pourrait être de sélectionner le point le plus proche pour chaque trajet via `ST_Distance` de PostGIS et un `GROUP BY trip_id` SQL dans une première requête.

Puis de réinjecter ces IDs de Point les plus proches type : `Trip.select('trips.*, point_a.id as point_a_id').joins('INNER JOIN points AS point_a ON trips.id = point_a.trip_id').where(point_a: { id: points_ids })`

**Comment by AlexBillbao** [comment]
@nicolasleger le debog que tu proposes, tu peux le transformer en PR ?

On ajoute ça à la liste des priorités, car ca a l'air "quasiment réglé", en tout cas, tu vois ce qu'il faut faire apparemment !

**Comment by nicolasleger** [comment]
@AlexBillbao Bonjour,

Je prépare un correctif mais pouvez-vous me préciser le comportement attendu en terme de retours et d’ordre dans les résultats.
Car même en ne précisant qu’un départ un trajet semble pouvoir appairer 2 fois, mais c’est peut être intentionnel et le prix pas forcément adéquat avec la recherche.

**Exemples**

- avec les lettres à équidistance sur une ligne de A à F, lettres adjacentes considérées proches par la recherche géolocalisée autour
- si j’ai un trajet 1 qui fait A -> B -> D -> E -> F le 14
- si j’ai un trajet 2 qui fait B -> C -> E -> F le 15

**i) Je recherche les trajets au départ de C :**

- retours : pour le trajet 2 dois-je retourner C -> E ET C -> F ou uniquement C -> F avec étape E ?
- retours : et si uniquement un quel prix afficher ?
- ordre : dois-je afficher 2 avant 1 (car départ de C plus proche que départ B ou D ou bien uniquement ordonner par date tant que les villes matchent ?)

**ii) Je recherche les trajets à l’arrivée pour E ?**

- retours : pour le trajet 2 dois-je retourner B -> E ET C -> E ou uniquement B -> E avec étape C ?
- retours : et si uniquement un quel prix afficher ?
- ordre : même questions que précédemment

**ii) Je recherche les trajets de C à E**

- retours : pour le trajet 1 dois-je retourner B -> E ET D -> E ou uniquement B -> E avec étape B ?
- retours : et si uniquement un quel prix afficher ?
- ordre : même questions que précédemment

**Comment by maxb29** [comment]
Bonjour @nicolasleger,

pour moi:

- Les 2 étapes exactement à la même distance du point recherché, ca n'arrivera quasiment jamais, même en arrondissant au km. Si ca arrive , on peut afficher les 2 trajets.
- Ce qui est important c'est de garder l'affichage de l'ensemble du trajet + étapes lors de la consultation de l'annonce (comme c'est le cas actuellement), en faisant ressortir (gras, foncé ...) la portion recherchée 
- l'ordre d'affichage des résultats doit rester chronologique

Je laisse Alex donner son avis ;)

**Comment by nicolasleger** [comment]
Testable sur https://cl-139.herokuapp.com/

Et en tests unitaires via `bundle exec rspec spec/models/trip_spec.rb`

**Comment by AlexBillbao** [comment]
Hello Nico. Aurais-tu un moment demain pour se rappeler ?
Pour refaire un point et entre autres envisager un protocole pour tester ta proposition !

**Comment by nicolasleger** [comment]
@AlexBillbao hello, via téléphone

**Comment by AlexBillbao** [comment]
On peut fermer ca non ?

**Comment by nicolasleger** [comment]
Fixed
