### ISSUE TITLE
Afficher le prix des étapes dans une annonce

### ISSUE THREAD

**Issue by ndelavergne** [covoiturage-libre/covoiturage-libre#140]
### Comportement actuel
Je cherche une annonce Toulouse>Bordeaux
je clique sur une annonce Toulouse>Rennes et je n'ai que le prix global
https://www.screencast.com/t/07C5kIWvr0M

### Comportement attendu
en fonction de la recherche c'est sans doute compliqué, mais au moins il faudrait trouver le moyen d'afficher le prix des étapes sur l'annonce

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by Poussinou** [comment]
Resolved by the issue above. Currently in production and works fine.
