### ISSUE TITLE
l'ordre des étapes ne s'inverse pas lorsque l'on publie le retour

### ISSUE THREAD

**Issue by ndelavergne** [covoiturage-libre/covoiturage-libre#143]
### Comportement actuel
J'ai récemment rentré deux trajets (aller et retour) sur covoiturage-libre, en utilisant la fonction "publier le retour".
Or on m'a fait remarquer que l'ordre des villes étapes était incorrect pour le retour.
Effectivement, l'aller étant A => B => C => D, le retour est affiché D => B => C => A.
J'imagine un bug dans la façon dont cette fonction est codée.

(signalé via la hotline)

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by AlexBillbao** [comment]
issue crée en double : https://github.com/covoiturage-libre/covoiturage-libre/issues/133

**Comment by Poussinou** [comment]
Fermeture en faveur de l'issue 133
