### ISSUE TITLE
Hotline - Validation du code HTML - 2erreurs

### ISSUE THREAD

**Issue by MickaelC87** [covoiturage-libre/covoiturage-libre#145]
### Comportement actuel

E-mail de Pierre (pierre@couderc.eu) reçu sur l'adresse de la hotline.

2 erreurs mineures dans la validation du code HTML
Lien : https://validator.w3.org/nu/?doc=https%3A%2F%2Fcovoiturage-libre.fr%2F

[] Développement
[] Production

**Comment by webplate** [comment]
Résolu sur la branche master. Je ferme :)
