### ISSUE TITLE
Hotline - Actualisation des e-mails dans la messagerie de la hotline

### ISSUE THREAD

**Issue by MickaelC87** [covoiturage-libre/covoiturage-libre#148]
Lorsque je clique sur la flèche pour actualiser les e-mails, il s'affiche ceci : 
![2017-01-20_11h27_30](https://cloud.githubusercontent.com/assets/24842927/22146029/a93f6258-df03-11e6-91ab-9b6abbc6ac85.png)

Et si je clique sur Détails, ceci:
![2017-01-20_11h27_40](https://cloud.githubusercontent.com/assets/24842927/22146052/b70af852-df03-11e6-8e18-5d049cf3bb6e.png)

Est-ce un vrai bug ou bien on peut ignorer ?

**Comment by AlexBillbao** [comment]
Tu récupères les messages sur un logiciel mail installé sur ton ordi ?

N'est-il pas "plus simple et centralisé" de s'occuper de la hotline via le gmail sur navigateur ?
