### ISSUE TITLE
Comment aider avec les fautes d'orthographe ?

### ISSUE THREAD

**Issue by Goutte** [covoiturage-libre/covoiturage-libre#149]
Bonjour !

J'ai trouvé une coquille dans le texte, et je voulais la corriger en deux-deux, et puis ça me faisait une excuse pour commencer à contribuer à cette belle aventure...

Une recherche m'indique que la coquille se trouve dans ce fichier :
https://github.com/covoiturage-libre/covoiturage-libre/blob/master/db/seeds/pages.seeds.rb

Je me doute bien que c'est un dump, et qu'il ne faut pas la corriger directement dedans... Comment faire ?
Kate refuse d'éditer le fichier car ses lignes sont trop longues.

---

Edit: j'ai compris. On est _obligé_ de passer par le CMS, non ?

**Comment by ndelavergne** [comment]
Bonjour,
Oui c'est par le CMS, pouvez-vous me dire quelle faute se situe sur quelle page ?

**Comment by Goutte** [comment]
Dans la FAQ:

```
J'aimerai vous aider, comment je fais
J'aimerais vous aider, comment je fais
```
(deux fois)

---

D'expérience, il est judicieux et de bonne pratique d'avoir ce genre de _fixtures_ dans des fichiers yaml, qui permettent de découpler les données du _framework_, ainsi que de lire et d'éditer le contenu directement dans le fichier, et aussi de se débarasser des horreurs comme `\r\n`. Le _CMS_ peut toujours exister, pour le _WYSIWYG_ mais il ne devrait pas préclure la lecture et l'édition directe des données. Bref, mes deux centimes, car j'ai déjà fait cette erreur moi aussi par le passé.

**Comment by AlexBillbao** [comment]
Je signale une autre faute à traiter sur la page de conformation de saisie d'une annonce (avant confirmation par mail).  ECRIRE "duppliquer"  et pas "dupllique".. il manque le r de l'infinitif.
![confirmation saisie annonce](https://cloud.githubusercontent.com/assets/24801105/22861936/a6519ede-f124-11e6-90ee-9456a0264cd2.png)

**Comment by Poussinou** [comment]
N'hésitez pas à signaler toute nouvelle faute d'orthographe ou de syntaxe ici même. Si vous pensez pouvoir améliorer certaines tournures, ou avez des idées de nouveaux textes, n'hésitez pas non plus :)

**Comment by Poussinou** [comment]
En relation avec #127

**Comment by thony8** [comment]
Attention, coquille sur le nom du framework dans la page des missions (surligné en gris)
![capture d ecran_2017-04-03_23-59-15](https://cloud.githubusercontent.com/assets/7198108/24633574/92a34578-18c9-11e7-8bb7-4e846d643363.png)

**Comment by guapyo** [comment]
Pour surcharger la réponse de @thony8 sur la même page:
Remplacer "web responsive" par "responsive-design" ou "design adaptatif"
Remplacer "Android et iTunes" par " Android et iOS"

**Comment by AlexBillbao** [comment]
@Goutte Je viens de corriger via le CMS :
. "J'aimerais vous aider, comment je fais" (avant il y avait écrit "j'aimerai erreur futur/conditionnel)

@thony8  j'ai changé "ruby on trails" > "Ruby on Rails 5".
@guapyo  j'ai corrigé "web responsive" > "design adaptatif
                                 "iTunes > iOS ( hihihi !)

------
Il faudra une Pull Request pour modifier la faute que j'ai décris en commentaire sur la page de confirmation de saisie d'une annonce ("Duppliquer" et pas "Dupplique"). Qui peut la faire (je sais pas faire) ?

Pour les fautes sur le HelloAsso #127 je vais demander les accès à @ndelavergne  !

Alex

**Comment by webplate** [comment]
Plus de fautes dans le code de l'application. Je ferme l'issue.
