### ISSUE TITLE
Ajout demande trajet passager

### ISSUE THREAD

**Issue by BSibille** [covoiturage-libre/covoiturage-libre#155]
### Comportement actuel
Il n'y a plus les demandes de trajets passager.
Or ça revient dans les mails...
A mettre en place quand on pourra lier à une demande de trajet passager une fonctionnalité d'alerte mail quand quelqu'un post un trajet qui correspond.

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by ndelavergne** [comment]
Pour ma part je ne pense pas qu'il faille revenir en arrière sur la suppression de cette option, qui était plutôt un miroir aux alouettes qu'autre chose à mon sens. (mais je me trompe peut-être). Les conducteurs ne viennent pas chercher des passagers sur notre site. (ou alors, quand ils déposent une annonce, cela devrait leur montrer les demandes correspondantes...).
Mettre en place les alertes me semble bien plus intéressant pour répondre à la question. 
On pourrait tout à fait imaginer une boîte sur la home, indiquant "les trajets les plus demandés en ce moment" à partir des alertes actives.
