### ISSUE TITLE
Pas de vérification d'email lors des envoi de messages

### ISSUE THREAD

**Issue by wtoscer** [covoiturage-libre/covoiturage-libre#157]
### Comportement actuel
Lorsque quelqu'un envoie un message en mettant une adresse email non valide, le message part quand même. L'annonceur est donc dans l'impossibilité de répondre...
![screenshot_20170228-091215](https://cloud.githubusercontent.com/assets/4253690/23396880/2dda47ca-fd96-11e6-8c9b-270749def931.png)

### Comportement attendu
Le message ne devrait pas partir, et un texte informatif devrait apparaitre pour la personne envoyant le message

### Étapes pour reproduire le problème
Envoyer un message sur une annonce en mettant "test" dans le champ email

[] Développement
[X] Production

**Comment by AlexBillbao** [comment]
Le meme probleme de non verification des emails se posent:
. en dépot d'annonce
. lorsqu'on contacte la hotline.

Pour le dépot d'annonce, Thomas a apparemment déjà mis en place une fonction pour vérifier si le email saisi est syntaxiquement correct ( avec un @ et un . suivi d'un nom de domaine x ou y). Cette fonction ne tourne apparemment pas lorsque l'on écrit à un conducteur ...

les solutions sont :
. mettre ne place une vérification syntaxique pour le form de contact conducteur (et pou Slaask aussi)
. Cela ne suffisant pas à vérifier la véracité du email mettre en place:
-> 1 double champ de saisie '1 saisie, et 1 "retapez votre mail pour le confirmer"
-> Pour les abrutis qui s'amuseraient à écrire 2x un mauvais mail, mettre en place un système qui envoie des requetes pour vérifier que le email indiqué existe vraiment : 
http://testermail.outils-webmaster.com/

**Comment by wtoscer** [comment]
Il n'y a pas forcément besoin de valider si l'email existe vraiment, mais déjà au moins valider la syntaxe serait un plus.
Surtout si la fonction existe déjà, ça ne doit pas coûter grand chose :)

**Comment by didierClin** [comment]
On peut ajouter la vérification que l'email entré reponde au format correct comme lors de la saisie du trajet.

**Comment by webplate** [comment]
Mainly fixed in a small PR implementing a basic check (same as for the announce posting) to the send message email field. It's a good practice I think to check for the email format here.

**Comment by webplate** [comment]
@wtoscer et voilà :) un petit patch #175
