### ISSUE TITLE
Liste des villes ne s'affiche pas sur le formulaire de recherche

### ISSUE THREAD

**Issue by d-stephane** [covoiturage-libre/covoiturage-libre#158]
Hello,
Voulant faire une recherche sur la home page, j'ai commencé à entrer "paris". Normalement une liste déroulante doit apparaitre, mais là, rien. Seul l'icône pour patienter est active et aucune liste n'apparait donc impossible de choisir une ville et d'obtenir un résultat de recherche. Problème présent avec les deux champs de saisie de ville.

Système : Debian Jessie
Navigateur : Firefox 51.0.1 (dernière mise à jour)

J'ai déjà utilisé le site sur mon système avec une version moins récente de Firefox et il n'y avait pas de soucis.

**Comment by AlexBillbao** [comment]
Bonjour Stéphane, l'outil de suggestion de ville (click obligatoire pour que les recherches fonctionnent hélas) a en effet bugé hier Mardi 2 mars de la fin de matinée jusqu'à 16h30. Ce bug ponctuel est donc résolu; tu peux fermer cette issue.

**Comment by d-stephane** [comment]
Oui, en effet plus de soucis. J'avais pas eu l'occasion de revenir sur le site depuis aujourd'hui. Tout est nickel :-)
