### ISSUE TITLE
Comment simplifier le setup de dev ? (pour favoriser les contributions)

### ISSUE THREAD

**Issue by pimpin** [covoiturage-libre/covoiturage-libre#164]
J'avais choisi ce projet comme exemple de projet open source de la _vrai vie_ pour illustrer une formation Ruby.
Nous étions sous environnement Windows et ce fut une galère sans nom pour faire l'installation.
Mais même sous environnement Unix [le setup](https://github.com/covoiturage-libre/covoiturage-libre#install) est trop lourd.
De quoi refroidir les velléités de bien des contributeurs.

Pour simplifier cela, je vois 3 axes de travail :

1. rédiger des scripts en s'inspirant des [pratiques de GH](https://githubengineering.com/scripts-to-rule-them-all/) -cela commencerait en v0 par un check de config; pour aller jusqu'au setup complet ca va etre coton de scripter et maintenir pour les différentes configs`-,
2. rendre un maximum de dépendances optionnelles dans les environnement de dev et de test (avec des fonctions dégradées mais toujours disponibles en cas de rupture ou d'absence de dépendance; cela renforce au passage la résilience du service global), -je pense à Elasticsearch et éventuellement à Postgis-
2. compléter les seeds de dev pour ajouter une base mini de villes ainsi qu'une activite fictive de demo ( historique et courant ). 
3. [_dokeriser_](http://ericlondon.com/2016/10/29/dockerize-rails-development-environment-integrated-with-postgresql-redis-and-elasticsearch-using-docker-compose.html) les environnements comme le fait [Discourse](https://github.com/discourse/discourse) par exemple. - je n'ai pas encore d’expérience de ce type, mais ça me démange-

Que pensez vous du besoin de simplifier le setup d'un env de dev ?
Que pensez vous des pistes proposées ?

En attendant vos retours je creuse pour documenter le fonctionnement dégradé d'app rails + ES sans serveur ES.

**Comment by pimpin** [comment]
Hey @nicolasleger [your PR](https://github.com/covoiturage-libre/covoiturage-libre/pull/160) seems great.
Not yet tested, but single click Heroku deploy will help a lot to dev.

Any comment or suggestion to facilitate dev env setup ?

**Comment by nicolasleger** [comment]
@pimpin thanks for the idea, I updated the PR.

Bonjour,

Je me joins à cette idée, l'intérêt est non seulement pour le dev mais aussi que d'autres personnes puissent réutiliser la plateforme, exemple pour un festival ou événement.

Dans les points peut être ajouter :

- Documenter les variables d'environnements / options / paramétrages
- Documenter la structure globale du projet, les flows (par exemple d'une annonce de covoiturage)

- Définir des guidelines pour contribuer
- Tests auto
- Outils de qualité du code et documentation

**Comment by Poussinou** [comment]
Pour la réutilisation pour un festival ou un événement, l'objectif ça serait de permettre aux organisateurs de l'événement d'avoir une sorte de page spéciale pour eux sur le site entre guillemet, et aussi une API qui permettrait aux participants de l'événement de déposer des annonces sur covoiturage-libre directement depuis leur site.

Je ne suis moi même pas assez technique pour pouvoir effectuer toutes les taches dont vous parlez ici.

Par contre comme dis sur une de tes PR @nicolasleger je peux clairement faire des guidelines pour contribuer, que voudriez voir apparaitre dedans? Les principales Issues à résoudre, comment commenter son code?

**Comment by nicolasleger** [comment]
Très bonne idée les guidelines et le wiki, par contre pas éditable semble-t-il par des personnes en dehors de l'équipe.

Pour les événements oui pour les pages sur CL mais disposer de son propre serveur et données est aussi utile.

Merci

**Comment by Poussinou** [comment]
J'ai modifié un paramètre pour le wiki, peux-tu me dire si tu peux essayer de pousser des modifications dessus maintenant?

Les propres serveurs et données seraient aussi consultables depuis CVL directement pour toi?

**Comment by nicolasleger** [comment]
Je confirme je peux éditer et ajouter des pages au Wiki. 👍 

Je vois deux options à offrir soit héberger sur CVL avec une page par événement et sinon l'option de lancer sa propre plateforme (faudra prévoir de modifier le style, nom ...).

**Comment by Poussinou** [comment]
Super si vous pouvez modifier le wiki :-)
Les "gérants" de l'association  veulent éviter la multiplication de plateformes pour garder une offre la plus grande possible. C'est aussi mon avis. Après pourquoi pas des déclinaisons dans d'autres pays, mais avec une base de donnée partagée pour permettre l'interopérabilité, d'où une sorte d'API. Pour ce qui est des événements, le jour où cet autre API/système sera en place, tous les événements seront les bienvenus.
Cependant, avoir la possibilité de changer nom/style/interface... du site est important en effet je suis d'accord avec toi, et l'une de tes PR qui va dans ce sens fait plaisir à voir!

**Comment by pimpin** [comment]
C'est certain qu'il faut favoriser l'agglomération des interfaces pour rassembler les offres et les demandes le plus largement possible et favoriser ainsi les probabilités de correspondance.
C'est bien pour le wiki.
Pour la section/page de contribution, on devrait s'inspirer d'autres projets open-source.

Une question se pose sur la langue d'échange utilisée.
Pour l'heure je crois que tous les contributeurs sont francophones nativement. Ne pas choisir l'anglais c'est amputer sérieusement le vivier de contributeurs et d'extension du réseau de plateformes a l'étranger.
Mais abandonner le Français est peut etre handicaper les capacités de dev du groupe actuellement constitué...

**Comment by Poussinou** [comment]
@pimpin Les contributeurs actuels sont tous francophones en effet, mais j'essaie de répondre le plus possible en anglais quand la discussion est lancée en anglais. Passez cette conversation en anglais ne me dérange pas outre mesure, après c'est vrai que c'est plus simple de parler français entre nous. Si passer en anglais ici ne vous dérange pas alors je suis pour.
Je pense faire un modèle pour les Issues et les PR où justement dedans on demanderait de parler anglais.

A quel projet open-source penses tu par exemple pour la page de contribution? Si tu as un lien dont je puisse m'inspirer je suis preneur.

**Comment by pimpin** [comment]
@Poussinou  vu que les utilisateurs sont francophones, je pense qu'il faut changer la premiere phrase du template pour etre moins directif et mettre a l'aise les non anglophone en leur proposant d'ecrire en Français.

Je ne serais pas si directif dans la consigne sur la langue. Cela pourrait retenir des retours de

>Issues in french are welcome : Etant donné que nous espérons développer notre communauté au delà des pays pays francophones, nous vous invitons a écrire ici en anglais si vous le pouvez. Votre contribution reste la très bienvenue dans la langue de Moliere.

Pour l'exemple de guide de contribution, on pourrait s'inspirer de [celui de Rails](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html) en l'élaguant sérieusement.

Sinon j'ai trouvé un template [la](https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md).

**Comment by Poussinou** [comment]
@pimpin Ok j'ai fais les changements dans le template, et mis le tout sur le dépôt principal. Je prendrai le temps de faire le template de contribution un moment où j'aurai du temps pour me poser vraiment. tes modèle sont pas mal.

**Comment by wayglem** [comment]
Hello guys,

I want to contribute but the dev setup seems to be complicated especially for someone that do not know the rails environment. @pimpin mentioned using Docker would you be interested if I do a docker-compose for the dev env? 
Is there any way to chat with someone who knows the environment already?
(et oui je parle français)

**Comment by Poussinou** [comment]
Hi @wayglem

Yep, as discussed here the dev setup is complicated, we want to simplify it to improve the contributions and the productivity.
A docker compose would be definitively a good idear, f you want to do it.

Personally, I'm not skilled enough to explain the environment, I do not program for the project because I do not know enough about ruby ​​or web development. @tbh can explain the environment since he was the main developer but he is very busy right now

**Comment by nicolasleger** [comment]
hi @wayglem @Poussinou

I started a Docker config at https://github.com/nicolasleger/covoiturage-libre/commit/de9aa3c63faca4c7237800af658ed9efdd37f6b1
But I still have a problem with networking between app and database, getting error `PG::ConnectionBad: could not translate host name "postgres" to address: Name or service not known`.
If it helps or you want to dig in it, feel free.

I already listed ENV variables in another PR https://github.com/covoiturage-libre/covoiturage-libre/pull/160/files

Regards

**Comment by wayglem** [comment]
Hello @nicolasleger 
I tried to go from your docker-compose file but didn't have any luck. It keeps telling me "could not connect to server". However the database is listening (tried with pgadmin...
I will try asking someone at work tomorrow and will try again this week.

**Comment by webplate** [comment]
Hello everyone ! Thanks for your work on this important project :) I just managed to run the site for dev on my ubuntu 16.04 and the process was a bit tricky (first time with rails...). I wonder... before writing scripts or going to docker wouldn't it be simpler to provide a simple tuto for running it ? I would like to add a tuto for ubuntu 16.04 on the wiki !

**Comment by webplate** [comment]
Well I didn't know the wiki was open to anyone without pull requests :) Should I remove the tutorial ? What do you think of it ?

**Comment by Poussinou** [comment]
Hi @webplate thank you for wanting to contribute to the platform :)
As discussed in this Issue, we try to simplify the dev setup, and your contribution to the wiki is highly appreciated !
The wiki is open to everyone, so that everybody can explain the process and contribute to the simplification of the dev setup, and you clearly don't have to remove the tutorial !

I will put your name in the contributors list. Do you agree if I put this licence : https://creativecommons.org/licenses/by-sa/4.0/ on your work in the wiki (this will be the general licence for the wiki)

**Comment by webplate** [comment]
@Poussinou thanks for the approval ! I would really love to help on this project and hope to have a bit of free time for it ! Can you send me an invitation to the covoli.slack.com site ? I've updated my profile with my real name and added my email. Also cc by sa 4.0 is ok by me :)
Now for the delicate matter : How can I have access to the city geonames list ? It's really important to debug the site !

**Comment by Poussinou** [comment]
I do not own all the admin rights on every website we are using at this time, but I hope to have them in a few weeks (it's complicated to meet everybody IRL). Just use Github for the moment ;)
The same for the city list, I do not own the list right now, just be patient please

Ok I will update the wiki !

**Comment by webplate** [comment]
@Poussinou Yes get the keys please :) We need to be able to push to the main site otherwise the project is pointless. Thanks for your dedication !

I will complete the dev setup page in the wiki soon, with nice improvements :)
Keep tuned !

**Comment by webplate** [comment]
I have updated my tutorial for installing a functional dev environment of covoiturage-libre on ubuntu. It has all the  functionalities of the main website including mailing, elastic searching, admin account with CMS and posting announces. I'm really happy with it as it seems to work well, but as a total noob in ruby OR rails I'm really interested in any feedback. I hope it's not too much to ask :) 
https://github.com/covoiturage-libre/covoiturage-libre/wiki/Dev-setup-on-Ubuntu
C'est tout ce que ça te fait quand j'te dis qu'on va manger des chips !

**Comment by webplate** [comment]
I have a light PR in the hope of a simpler tutorial, and installation process :)

**Comment by Poussinou** [comment]
#191

**Comment by webplate** [comment]
Vu les liens d'autodéploiments sur scalingo et heroku, plus mon tuto sur le wiki. Je pense qu'on peut fermer cette issue.
