### ISSUE TITLE
Prix négatifs

### ISSUE THREAD

**Issue by thony8** [covoiturage-libre/covoiturage-libre#165]
### Comportement actuel

Il est possible de tomber sur une annonce qui affiche un prix négatif, ce prix devient nul (0 €) lors de l'accès à la fiche du trajet.
![capture d ecran_2017-04-03_23-45-41](https://cloud.githubusercontent.com/assets/7198108/24633235/bd3755e2-18c7-11e7-9603-0de683415b4f.png)
![capture d ecran_2017-04-03_23-45-58](https://cloud.githubusercontent.com/assets/7198108/24633241/c4423cd0-18c7-11e7-9b76-b7a184a317d3.png)

### Comportement attendu

Le prix devrait être positif.

### Étapes pour reproduire le problème

Chercher un trajet, mais cela dépend de l'annonce.
Pour le cas présent : 
- Ville de départ : Bordeaux
- Ville d'arrivée : Douvaine
- Date : 08/04/2017

[] Développement
[X] Production

**Comment by didierClin** [comment]
@thony8 
le prix du trajet global est bien controlé à la création (>0) mais ne l'est pas lors de l'ajout de prix d'une étape.
il suffit d'ajouter ce controle pour corriger le pb.

**Comment by Poussinou** [comment]
@didierClin merci pour la PR. Je devrai bientôt pousser les différentes PR les unes après les autres, il faut juste que je remette en place le site de test pour les tester indépendamment chacune.

**Comment by Poussinou** [comment]
This issue is resolved by the PR above. This is currently in production, and the problem does not happen anymore.

**Comment by thony8** [comment]
Je me permets de revenir sur cette issue, il est encore possible de trouver des prix négatifs : 

![capture d ecran_2017-07-01_12-18-47](https://user-images.githubusercontent.com/7198108/27761183-79ff739c-5e57-11e7-8d9d-1263b70cabe3.png)

Néanmoins j'ai l'impression que le problème vient de la définition des prix de chaque étape : 

![image](https://user-images.githubusercontent.com/7198108/27761192-9b24d9d6-5e57-11e7-9e68-368c492fa987.png)

**Comment by webplate** [comment]
This one is really ugly ! I'm working on a new validator for trip prices so I hope to fix this soon enough :)

**Comment by webplate** [comment]
#196 should fix this :)

**Comment by AlexBillbao** [comment]
Et oui c'est quand les utilisateurs ne respectent pas le mode d'indication du prix préconisé !
Il faut en effet comme l'indique ton pull vérifier que les prix sont biens croissants étape par étapes. Curieux de découvrir ce que tu as prévu comme "message d'erreur" pour prévenir l'usager qu'il a mal indiqué les étapes !

ATTENTION !
Si vous pousser cette PR on va ce retrouver avec un autre pb lié : 

Quand un conducteur qui a publié une annonce clique sur "créer le retour", les étapes se mettent en ordre inverse, mais sans recalculer les prix, du coup les prix se retrouvent alors en mode décroissant, à voir donc en phase test !
