### ISSUE TITLE
Lien mort dans les CGUs / Deadlink

### ISSUE THREAD

**Issue by webplate** [covoiturage-libre/covoiturage-libre#171]
### Current Behavior 
The bottom link at https://covoiturage-libre.fr/cgus linking to https://covoiturage-libre.fr/calcul leads to a 404 not found error page.

### Expected Behaviour 
Seeing "des informations intéressantes sur le calcul du prix d'un trajet en covoiturage et sur la législation en vigueur."

### Steps to Reproduce the Problem  
Exploring CGUs

[] Development
[] Production

### Ideas for solving the problem / Implementing the new functionality  
Find this page back ! I'm interested I must admit. Or remove the misleading link.

**Comment by webplate** [comment]
Found it ! The link should point to /calculer and not to /calcul
I'll try a PR.

**Comment by AlexBillbao** [comment]
J'ai accès au backoffice admin du site, et de là j'ai pu modifier le lien hypertexte dans les cgus,
pas besoin de pull request !

il fallait en effet, /calculer au lieu de /calcul.

ISSUE À FERMER DONC !
ALex
