### ISSUE TITLE
Problem with the help button on Android

### ISSUE THREAD

**Issue by Poussinou** [covoiturage-libre/covoiturage-libre#178]
### Current Behavior 
When we open the website in a browser on a smartphone (here Android), we can click on the "help button" in the bottom right corner. On some devices, here Android 4.1.2, you do not have any button to close the dialog:
![manque bouton android 4](https://cloud.githubusercontent.com/assets/19646549/25501974/0e53884e-2b95-11e7-9df3-4fdce4f9758a.jpg)
You still have one on Android 5.1:
![android 5 bouton present](https://cloud.githubusercontent.com/assets/19646549/25502009/2bb1d058-2b95-11e7-9053-351c834b7ff9.jpg)

That's a critical user experience problem. Also, if we close the tab of the website, and reopen another one, the dialog is still present.

### Expected Behaviour
To have a button in every case to close the dialog.
If we left the website with this dialog opened, he must be closed when we reopen it.

### Steps to Reproduce the Problem
- Open the covoiturage-libre.fr site on its smartphone
- Click on the help button
- Is there a cross to close the chat window? A way to return to the site? (This may depend on your android version)
- Close the tab, reopen another one with covoiturage-libre.fr
- Does the tchat window appear directly (without having clicked the question mark)?

[] Development
[] Production

### Ideas for solving the problem
Not sure if it's a problem from the website or the browser directly?
This bug was reported via the test-group on Facebook. The same problem happens on a windows phone.

**Comment by Poussinou** [comment]
@slaaskhq Hello, do you have any idea about this problem?

**Comment by AlexBillbao** [comment]
Le pb c'est là ca relève en effet pas du code covoiturage-libre mais su code de Slaask .. je leur ai déjà écrit via le compte d'admin du widget et ils n'ont jamais répondu ...
