### ISSUE TITLE
Modifier le rayon de recherche du site autour d'une ville donnée

### ISSUE THREAD

**Issue by Poussinou** [covoiturage-libre/covoiturage-libre#188]
### Current Behavior 
Lorsque l'on fait une recherche sur le site, les résultats retournés incluent des villes dans un certain rayon autour de la ville recherchée. On ne peut pas régler ce rayon manuellement, il est imposé par le site.

### Expected Behaviour 
L'objectif serait d'avoir une sorte de curseur pour dire dans un rayon de combien on veut chercher autour des villes de départ et d'arrivée.

### Steps to Reproduce the Problem  
Faites par exemple une recherche "Lamballe - Rennes", des villes alentours seront proposées, mais vous ne pourrez pas modifier le rayon où celles-ci peuvent être cherchées. L'objectif serait donc de permettre ce changement de rayon autour de Lamballe et de Rennes. 

[] Development
[] Production

### Ideas for solving the problem / Implementing the new functionality  
Utilisation d'un curseur. Faut-il en mettre un différent pour la ville de départ et celle d'arrivée, ou grouper les deux sous un même curseur?

(idée d'amelioration lue/demandée dans les "avis" de la page facebook du site, cette modif peut faire drastiquement baisser le nombre de trajets affichés, à prendre avec des pincettes...)

**Comment by maxb29** [comment]
En effet je pense que cette fonctionnalité est très importante. 
Il faudrait mettre un curseur différent pour départ et arrivée, avec les possibilités suivantes : 0, 10 , 30 , 50, 150km

En plus de la possibilité de changer le rayon manuellement, ce qui serait vraiment top c'est d'ajuster automatiquement le rayon par défaut en fonction du nombre de km entre ville de départ et arrivée.
Par exemple les personnes qui recherchent un Marseille -> Lille (1000km) , peuvent être intéressées par un Avignon -> Lille. Contrairement à une personne qui recherche Marseille-> Lyon (300km) , qui ne sera pas intéressé par Avignon->Lyon.

Je verrais bien quelquechose comme cela:
- trajet <30km : rayon recherche=10km
- 30<trajet<100 : rayon recherche=30km
-100<trajet<500 : rayon recherche=50km
-500<trajet : rayon recherche=150km

Condition pour avoir ce système , régler cette histoire de trajet dupliqué dans les résultats de recherche (due aux étapes dans le rayon de recherche, ca peut vite devenir genant avec des rayons de recherche étendus)

Et ajouter dans les résultats de la recherche, a combien de km de la ville recherchée est la ville affichée. 
Dans mon exemple : Avignon **(100 km de Marseille)** -> Lille

**Comment by Poussinou** [comment]
Redondance avec la 154, autant pour moi
