### ISSUE TITLE
Installer un bandeau lilo pour accroître les microdons

### ISSUE THREAD

**Issue by ndelavergne** [covoiturage-libre/covoiturage-libre#189]
Voici le code bannière pour l'intégration sur le site :

    <div id="lilo-gt2covoiturage-libre-fr"></div>
    <script async src="//www.lilosearch.org/img/dyn/js/wid/gt2covoiturage-libre-fr.js"></script>

mettre sur une page test dans un premier temps 
envoyer l'url de cette page à Clément Le Bras <clement@lilo.org> pour vérification que tout fonctionne bien avant de la mettre sur tout le site. 

ça doit donner https://www.screencast.com/t/GFkjUlyk6
ça permet d'optimiser les dons via lilo, a priori de les multiplier par 5 à 10 (pour atteindre 2000 à 3000€/mois a priori très vite).

**Comment by ndelavergne** [comment]
Je précise que le partenariat avec Lilo ramène à l'association autour de 300€/mois actuellement.
La mise en place de cette bannière sur 3 ou 4 autres sites partenaires à trafic important (mais pas autant que celui de cvl) a permis de multiplier par 8 ou 10 les gouttes données.
https://www.lilo.org/fr/covoiturage-libre-fr/?utm_source=covoiturage-libre-fr

**Comment by Poussinou** [comment]
@webplate Prioritaire à mettre en place si tu as le temps ;)

**Comment by Poussinou** [comment]
@webplate Y a moyen de le voir sur le site test, le bandeau en action? Je vais écrire à Clément de Lilo, pour qu'il jette un coup d'oeil, sauf si tu l'as déjà fait ou que tu veux le faire?

**Comment by webplate** [comment]
Voici ma proposition: #211 
à tester sur https://covoli-dev-pr211.scalingo.io/

**Comment by Poussinou** [comment]
Oups ok pardon j'ai mis sur la PR que j'allais le faire mais vas-y toi, tu seras plus à même d'en discuter. J'essaye de me rendre utile vu que je peux pas aider pour la programmation, donc si tu veux que je le fasse c'est sans problème :)

**Comment by webplate** [comment]
Ah, oups pour moi alors, je l'ai fait mais j'aurais du laisser ta motivation s'exprimer. Merci Poussinou !

**Comment by AlexBillbao** [comment]
Merci Glen pour ce 1er test. Il me semble qu'un bandeau en surimpression serait préférable à une intégration au même plan que les contenu comme tu l'as fait. je pense qu'il est mieux que ce soit une surcouche d'info bien visible (d'où la surimpression) et que les gens puissent la fermer, ou la laisser sans qu'elle gêne leur recherche.

Glen, peux-tu insérer la miniature de la goutte d'eau Lilo à côté des liens ? Ca matérialise bien graphiquement que cette encart concerne Lilo, en sus des mentions typographiques.
Concernant ces dernière, je suggère de retoucher le texte parce que le texte proposé sur le screencast n'est pas très clair. Voici une proposition de texte, à débattre : 

_Covoiturage-libre.fr est un site associatif à but non lucratif dont le service de mise en relation entres covoitureurs est gratuit. Cependant le développement a un coût. Nous sommes financés par les dons des usagers qui soutiennent notre démarche. Grâce au moteur de recherche Lilo, vous pouvez nous financer sans bourse délier, simplement en faisant vos recherches web avec Lilo, et en nous donnant les "gouttes d'eau" que vous gagniez à chque recherche web. Merci pour votre soutien !
---

Pour "contacter Clément de Lilo", comme dit dans le brief et au téléphone, mieux vaut que Glen et Nico se focalisent sur la production de code, et que tout ce qui peut être fait par des non-codeurs le soit par des non-codeurs. Ne nous dispersons pas, la liste des tâches techniques est longue, donc soyons méthodiques :-D. On s'occupera de recontacter Clément en tant voulu pour lui annoncer qu'on a enfin mis le bandeau quand il sera prêt !

**Comment by webplate** [comment]
Merci Alex pour ton texte qui est bien meilleur à mon avis (le coup du mois d'utilisation je trouvais ça louche).
Par contre il vaut mieux répondre à la proposition sur le fil #211 (ici on discute du problème).
