### ISSUE TITLE
Réponse automatique du mail directement vers l'usager

### ISSUE THREAD

**Issue by Poussinou** [covoiturage-libre/covoiturage-libre#204]
Proposition venant du groupe facebook de test, vous pouvez la voir [ici](https://www.facebook.com/groups/covoiturage.libre.test/permalink/513790245633330/) si vous êtes dans le groupe.
### Current Behavior
A l'heure actuelle, lorsqu'un passager écrit un mail à un conducteur, le fait de répondre automatiquement à ce mail reçu par le conducteur renvoie une réponse à Covoiturage Libre, à l'adresse utilisée pour contacter les conducteurs mais qui ne doit pas recevoir de réponse.

![image](https://user-images.githubusercontent.com/19646549/29845502-59878768-8d13-11e7-9bbf-2a1ce7c8a471.png)

### Expected Behaviour 
Le fait de cliquer sur réponse automatique devrait mettre automatiquement l'adresse du futur passager dans la barre d'adresse...

### Steps to Reproduce the Problem  
Mettre une annonce en tant que conducteur, puis s'envoyer un mail et essayer d'y répondre automatiquement, cette action renvoie un message vers Covoiturage Libre.

[] Development
[x] Production

### Ideas for solving the problem
Spécifier le champ "Reply-to" dans le header du mail reçu par le conducteur. Permettrai d'être plus user-friendly et de fluidifier les choses pour les utilisateurs qui sont habitués à ce bouton 😃

**Comment by nicolasleger** [comment]
Il y avait déjà le Reply To d'ajouté dans le code via https://github.com/covoiturage-libre/covoiturage-libre/blob/master/app/mailers/user_mailer.rb#L27
À vérifier dans la source brut " raw " du message.

**Comment by maxb29** [comment]
Dans Gmail ca me remplis bien l'adresse de l'expéditeur, lorsque je cliques sur "répondre", pour moi on peut fermer l'issue
![image](https://user-images.githubusercontent.com/25374637/34156765-e9a93294-e4be-11e7-97e1-a608e2d41175.png)

**Comment by nicolasleger** [comment]
Done
