### ISSUE TITLE
Email invalide

### ISSUE THREAD

**Issue by Plinz** [covoiturage-libre/covoiturage-libre#207]
### Current Behavior 
Lors de l'ajout d'un trajet, à la validation la page indique une erreur lorsqu'il y a un espace vide au début ou à la fin du mail renseigné. Sur téléphone la prédiction rentre automatique le mail avec un espace à la fin, c'est donc assez courant pour moi d'avoir cette erreur. 

### Expected Behaviour 
Pas d'erreur. 

### Steps to Reproduce the Problem  
Faire un nouveau trajet avec un espace vide dans le champs email au début ou à la fin. 

[] Development
[X] Production

### Ideas for solving the problem / Implementing the new functionality  
La regex devrait échapper les caractères vides en début et en fin de champs.

**Comment by AlexBillbao** [comment]
Salut @Plinz , et bienvenue dans l'équipe :-D

Je suis Alex, je supervise la hotline et participe au développement du projet.
Nous avons en effet observé ce pb de Regex grâce à des plaintes sur la hotline, mais on avait pas ouvert jusque là d'issueà ce sujet, faute d'avoir assez de contributeurs pour être sûr que l'issue soit traitée. À Présent ca va bouger à nouveau (nombreuses contributions à prévoir de @nicolasleger  et @webplate qui reprennent le flambeau du dév technique.

Ils n'auront cependant pas la possibilité de tout traiter, ainsi toute contribution est la bienvenue !

Plinz, es-tu en mesure de proposer la bonne commande Regex pour résoudre cette issue ?

Merci, Alex.

**Comment by Plinz** [comment]
Salut @AlexBillbao,

Je peux proposer : 
\s*(.+@.+\..+)\s*

Cette regex parait trop simple mais étant donnée qu'un email de validation est envoyé il ne sert à rien de trop complexifier.
Les \s* permettent de matcher les caractères vides en debut et fin de chaine, il faudra donc penser récupérer la premier occurence du match group qui devrait contenir l'email.

Plinz
