### ISSUE TITLE
[Feedback Tests] Boosted main cities appeared first but not matching

### ISSUE THREAD

**Issue by nicolasleger** [covoiturage-libre/covoiturage-libre#230]
### Current Behavior 

> Quand je rentre Vannes, on me propose Cannes en premier, avant Vannes. Curieux non ?

### Expected Behaviour 

Vannes first and Cean after.

### Steps to Reproduce the Problem  

[x] Development
[] Production

### Ideas for solving the problem / Implementing the new functionality  

Adapt search boosting coeffiicent.

**Comment by nicolasleger** [comment]
To test:

```
class City < ApplicationRecord
  alias_attribute :postcode, :postal_code
  alias_attribute :city, :name
end
City.create!([{"name":"Cannes","postcode":"06400","country_code":"FR","lat":43.55,"lon":7.016667},{"name":"Vannes","postcode":"56000","country_code":"FR","lat":47.666667,"lon":-2.75}])
```

**Comment by AlexBillbao** [comment]
En début de Saisie, appliquer la règle "First letters"

**Comment by nicolasleger** [comment]
Corrigé en production
