### ISSUE TITLE
Price are rounded

### ISSUE THREAD

**Issue by nicolasleger** [covoiturage-libre/covoiturage-libre#233]
### Current Behavior 

Auto round by Rails.

### Expected Behaviour 

- only accepts rounded integer by user
- show errors if not

### Steps to Reproduce the Problem  

[] Development
[] Production

### Ideas for solving the problem / Implementing the new functionality  

Seems to comes from database `points#price` and `trips#price` are both `integer` and not decimal format. Might be wished if cents everywhere.

**Comment by nicolasleger** [comment]
@Poussinou It seems already the case in production isn't it ?

**Comment by Poussinou** [comment]
Yes it is

**Comment by nicolasleger** [comment]
Fixed with the last PR.
We would need another issue to manage cents if we wished to.
