### ISSUE TITLE
Upgrade ElasticSearch database on Scalingo

### ISSUE THREAD

**Issue by nicolasleger** [covoiturage-libre/covoiturage-libre#239]
Scalingo allow us to upgrade the ElasticSearch database to a patched version.

- https://www.elastic.co/guide/en/elasticsearch/reference/2.4/breaking-changes-2.4.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-5.0.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-5.1.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-5.2.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-5.3.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-5.4.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-5.5.html

### Current Behavior 

- ElasticSearch 2.3.4

### Expected Behaviour 

- ElasticSearch 5.5.3

[x] Development
[x] Production

### Ideas for solving the problem / Implementing the new functionality

- Use the button in the Scalingo > Addons > ElasticSearch Dashboard > Upgrade button at the bottom right
- ⚠️ Upgrade will make the database unavailable during the process

**Comment by nicolasleger** [comment]
Done in the test env, it took 2 minutes.

⚠️ Data is good but ranking in cities results has changed a bit.
First letters are not before multiple occurrences matches.

## 2.2.3 : First letters on top
<img width="509" alt="2 2 3" src="https://user-images.githubusercontent.com/570901/32601567-5f8f3044-c543-11e7-8b98-c0b3deb15eb5.png">

## 5.5.3 : Multiple occurrences on top
<img width="582" alt="5 5 3" src="https://user-images.githubusercontent.com/570901/32601584-68d4fdaa-c543-11e7-9e33-74d5aeee5b98.png">

**Comment by Poussinou** [comment]
2.2.3 was better regarding the user experience

**Comment by nicolasleger** [comment]
Yes I will adapt the configuration to keep that behaviour.

**Comment by nicolasleger** [comment]
Might be linked with https://github.com/covoiturage-libre/covoiturage-libre/issues/230

**Comment by nicolasleger** [comment]
Now fixed on dev see related pull request

<img width="605" alt="screen shot 2017-12-06 at 01 17 24" src="https://user-images.githubusercontent.com/570901/33637806-4fb4ac9a-da23-11e7-80fd-7e198baa1539.png">

**Comment by AlexBillbao** [comment]
Oui par défaut il faut prioriser sur les premieres lettres des villes, 
mais lorsque la liste des villes suggérées se restreint il faut ouvrir à de nouvelles conditions:

Exemple: Ce qu'il se passe quand quelqu'un tape une ville avec une faute d'orthographe ou en omettant un article : Ex: L'ISLE SUR LA SORGUE. 

Si je cherche ISLE SUR SORGUE, je devrai pouvoir le trouver une fois que j'ai tapé suffisamment de caractères pour éliminer les autres possibilités. Ok je suis un abruti qui ne sait pas écrire le nom de ma ville, mais je devrai pouvoir trouver ma ville, sinon l'internaute lambda s'énerve contre le site.

Hors comme j'ai Omis le -L'- dès le début de ma saisie, ma ville n'apparaitra jamais.
![recherche ville - conditions](https://user-images.githubusercontent.com/24801105/34276340-453d238e-e6a1-11e7-9c16-ed5331f0f1a6.jpg)

Au fur et à mesure de la saisie des caractères, le nbre de suggestion se restreint, puis plus aucune suggestion. Dès qu'il n'y a plus de suggestions, et peut-être même avant, il faudrait désactiver le critère "first letters" pour passer au critère multiples occurences ou autres.

Il faudrait une évolution des critères en fonction de l'épuisement des suggestions.
On part du principe que l'usager a commencé par bien saisir les bonnes lettre de sa ville, puis quand les suggestions s'épuise, on réouvre pour envisager que l'internaute ai pu faire ds fautes de frappe, d'orthographe ou d'omission d'article.

----
PS: Y a-t-il d'autres critères de suggestions proposés par elastic Search, autres que les 2 suggérés ci dessus ?

PS2: Les liens hypertextes sont pour la plupart des ERROR 404 à ce jour.

**Comment by nicolasleger** [comment]
Done
