### ISSUE TITLE
How to rebuild postgre indexes 

### ISSUE THREAD

**Issue by MatthD** [covoiturage-libre/covoiturage-libre#352]
Hi,
It seems when there is a lot of request, problems with indexes on the postgre DB happen, 

### Steps to Reproduce the Problem 
Have an hight load average || requests,
seems to have. link with [another issue](https://github.com/covoiturage-libre/covoiturage-libre/issues/251)

[] Development
[X] Production

### Ideas for solving the problem / Implementing the new functionality
Please could you describe how to recreate/rebuild indexes.

**Comment by nicolasleger** [comment]
Hi, I described it there https://github.com/covoiturage-libre/covoiturage-libre/issues/251#issuecomment-343739399

**Comment by MatthD** [comment]
Thanks ! I think I can close this issue so .
