### ISSUE TITLE
Reprendre vos sources pour faire un site de covoiturage Animalier : Animaux sous Asso || Pet Carpooling for Non-Profit Org. that rescue them

### ISSUE THREAD

**Issue by Cathia-zee** [covoiturage-libre/covoiturage-libre#363]
Bonjour, 

J'ouvre cette issue dans le cadre d'une réutilisation de votre code pour la protection animale.

Je recherche depuis plusieurs années à faire un site de covoiturage pour les animaux sous associations que l'on a souvent besoin de transférer d'une ville à une autre, voire même entre pays frontaliers de la France, ou aussi entre les DOM et la métropole pour les amener chez une famille d'accueil ou un adoptant. 
J'avais préparé les specs et trouver un développeur web bénévole en 2016 mais qui a vite laissé tomber face à des problèmes techniques.

Nous avions choisi le nom du site et préparer un logo et une image header en attendant, avec d'autres personnes. Depuis 2015, j'ai aussi un hébergement (serveur mutualisé OVH avec 3db de libre). Je m'occupe d'un autre site pour la protection animale depuis 2015, développé par moi meme et un ami, avec wordpress plus des scripts php et une tache CRON chaque soir => Mise en relation de personnes se proposant Famille d'accueil et des Assos en recherchant dans le secteur géographique.

Le site pour le covoiturage n'a jamais vu le jour et le besoin est toujours la pour les associations qui actuellement utilisent des groupes facebook pour s'organiser et trouver des covoiturages et ça ne s'organise pas très bien justement. Les associations passent un temps considérable à partager encore et encore les mêmes recherches de trajet pour tomber sur une personne qui ferait ce trajet la dans cette période la.

**Le principe est le même, proposer des places, pour animaux, pour un trajet effectué normalement. En voiture mais aussi en train et avion.** 
Faire une recherche sur les trajets disponibles.
Villes étapes, villes à proximité, dates flexibles (Pour les animaux d'asso le besoin est très souvent flexible sur une période de 2 semaines).

**Mais aussi que les associations puissent poster une recherche de covoiturage.** 
Par exemple, ""recherche un covoiturage de Béthune à Valence pour 3 lapins entre le 1 et le 15 septembre max."".""recherche coavionage ile de la réunion à paris pour un chien"
Les animaux sont tous sous asso, en cas de problème l'asso qui réserve les places et qui couvre les animaux doit gérer elle-même avec le covoitureur (ou l'accompagnateur quand il s'agit de train ou avion.)
Le site ne fera qu'une mise en relation gratuite.

Le covoitureur peut proposer de prendre un animal totalement bénévolement ou demander un petit dédommagement. Pour le train ou l'avion l'association doit bien sur payer la place de l'animal.
Actuellement les gens faisant normalement un trajet en voiture, se propose bénévolement pour prendre un animal avec eux. 
Ce n'est pas du tout un business, c'est de l'entraide pour ces animaux victimes de la bêtise humaine : abandons et maltraitances.

Certaines assos ont tenté il y a quelques années de réserver des places blablacar tout en prévenant la personne que c'était pour un animal et d'obtenir l'accord, mais le site blablacar bloque systématiquement les messages (et donc réservation) en ce sens.

J'ai tenté de trouver des solutions par moi-même avec wordpress mais en vain, aucune extension n'était utilisable. Je n'ai pas vraiment de connaissances web, je peux bidouiller un peu le php, html, css... 
J'étais développeuse JAVA dans le passé, en autodidacte, j'ai appris aussi android, mais je ne suis pas du tout développeuse web et je n'ai jamais utilisé GitHub, juste des recherches pour trouver des solutions parfois.

Si vous me donniez l'accord de pouvoir réutiliser vos sources je pense pouvoir apprendre et m'adapter pour pouvoir mettre en place un site spécifique avec des infos propres à ce contexte. Ou alors si un de vos gentils développeurs, contributeurs se sentait optimiste et motivé à nous aider un peu ca serait top !

J'attends votre retour.

**Comment by Poussinou** [comment]
Bonjour,

Dans un premier temps, il faut savoir que le code source disponible ici ne reflète pas du tout le code actuel fonctionnement sur https://covoiturage-libre.fr/ (et redirigeant sur https://www.mobicoop.fr/ le nouveau nom de l'assos après sa transformation en coopérative).

Vous pouvez bien sûr réutiliser le code source ici en forkant. Il faut juste publier vos changements au code source pour que tout le monde puisse les voir (principe de l'open source). Il faut aussi créditer covoiturage libre, mais rien de bien méchant. Après je crois me souvenir que le déploiement du code actuellement dans ce dépot n'est pas une mince à faire.

Le mieux, c'est de contacter directement mobicoop qui pourront vous dire si ils peuvent accepter ce que vous demandez directement sur leur plateforme. Vous pouvez le faire ici : https://www.mobicoop.fr/contact

**Comment by Cathia-zee** [comment]
Bonjour, 

Je pensais que c'était justement ici qu'il fallait demander pour ce type de demande, comme expliqué dans la présentation du projet.
Je vais fermer cette demande et me débrouiller. 

Merci quand même.

**Comment by Poussinou** [comment]
Bonne chance
