### ISSUE TITLE
Règle d'écriture d'URL d'une annonce

### ISSUE THREAD

**Issue by thb** [covoiturage-libre/covoiturage-libre#37]
Avoir une URL du type `/trajet/lille-paris/xxxxx`

Utiliser le token de création en ID

**Comment by AlexBillbao** [comment]
Intéressant. Blablacar chiffre ses urls pour ne pas donner de lisibilité sur le no,bre d'annonces et de profils je suppose.  Je me sert des urls numériques incrémentées les une après les autres pour faire des suivis du nombre de nouveaux membres et nouvelles annonces sur freecovoiturage.fr Gomore et d'autres encore ... Trop facile pour connaitre les vrais chiffres de fréquentation de ce genre de site !

**Comment by thb** [comment]
Les URLs sont cryptées aussi chez nous
