### ISSUE TITLE
La ville de Lyon

### ISSUE THREAD

**Issue by ndelavergne** [covoiturage-libre/covoiturage-libre#60]
### Comportement actuel
La ville de Lyon qui est dans la base est "Lyon, 69061, cedex 06"

### Comportement attendu
ça devrait être Lyon, 69000 tout court non ?

je ne sais pas si ça touche d'autres villes.

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by thb** [comment]
J'ai enlevé les codes postaux en 'cedex', qui doivent il est vrai être enlevés. On pourra restester quand j'aurai redéployé.

**Comment by ndelavergne** [comment]
Il semble que la ville de Lyon ait juste disparu

**Comment by Poussinou** [comment]
Capture d'écran du 29/08/17 la ville de Lyon apparait correctement. Il n'y a plus les adresses en cedex.
![image](https://user-images.githubusercontent.com/19646549/29830088-7c680230-8ce1-11e7-8e66-8e3aedd1fafd.png)
