### ISSUE TITLE
Suggestion du prix d'un trajet et des étapes

### ISSUE THREAD

**Issue by ndelavergne** [covoiturage-libre/covoiturage-libre#81]
### Comportement actuel
pas de prix indiqué dans le champ prix

### Comportement attendu
proposer un prix moyen prérempli dans le champ prix du trajet total.
La formule : 5€ par 100km, en arrondissant au nombre entier le plus proche.
L'utilisateur peut soit laisser le prix indiqué, soit le modifier manuellement (y compris avec des flèches +et-, à voir)
Ensuite, ça calcule automatiquement le prix des étapes s'il y en a, en arrondissant à l'euro entier.

(ça devrait permettre d'afficher le prix d'une étape dans les résultats de recherche)

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by AlexBillbao** [comment]
Tant qu'il y a des bugs de calculs de kilomètres via la carte, c'est compliqué de se servir de cette information pour proposer un prix ..
