### ISSUE TITLE
Le champ téléphone doit être numérique

### ISSUE THREAD

**Issue by ndelavergne** [covoiturage-libre/covoiturage-libre#85]
### Comportement actuel
actuellement, le champ âge est bien numérique, mais le champ téléphone accepte une suite de lettres
http://screencast.com/t/5HoPxlO9irmq
le champ alphabétique est accepté
http://screencast.com/t/Ni8RNinjBOGu

### Comportement attendu
le champ téléphone aussi doit être numérique, avec un message d'erreur

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by thb** [comment]
En fait un téléphone peut comporter des espaces, des points, des parenthèses, un "+", etc. la vraie validation d'un téléphone est plus complexe que cela. Si tu veux pour en post MVPv2 je pourrai utiliser cette librairie https://github.com/daddyz/phonelib. Ok pour toi ?

**Comment by ndelavergne** [comment]
Effectivement sur le site actuel, on peut mettre n'importe quoi dans le champ téléphone. Donc on laisse comme ça pour l'instant, je sors l'item de MVP
