### ISSUE TITLE
ajouter un favicon

### ISSUE THREAD

**Issue by ndelavergne** [covoiturage-libre/covoiturage-libre#92]
Download the generated favicon and extract the contents to the root directory of your site.

[373c6697b4eb05dd0d2630ed172c197d.ico.zip](https://github.com/thb/covoiturage-libre-rails5/files/620473/373c6697b4eb05dd0d2630ed172c197d.ico.zip)

Include the following code in the head of your HTML document.

```
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
```

**Comment by thb** [comment]
bien mais dommage qu'il ne soit pas sur fond transparent

**Comment by thb** [comment]
Tu peux en faire une sur un fonds transparent et mettre le van au maximum de la largeur pour maximiser sa taille stp ? et bien centré verticalement également ^^

**Comment by ndelavergne** [comment]
fond transparent, largeur, vertical, ok.
après, deux versions, avec le camion transparent ou blanc. j'ai une préférence pour le camion blanc, je te laisse tester les deux.

fond du camion transparent aussi : 
[fc9a14cbd515b5ec59035f27a6e8ffa2.ico.zip](https://github.com/thb/covoiturage-libre-rails5/files/621524/fc9a14cbd515b5ec59035f27a6e8ffa2.ico.zip)

fond du camion blanc : 
[20671b343f4c3e86dba426c5e0df0686.ico.zip](https://github.com/thb/covoiturage-libre-rails5/files/621525/20671b343f4c3e86dba426c5e0df0686.ico.zip)

**Comment by thb** [comment]
Camion blanc, je préfère aussi

**Comment by ndelavergne** [comment]
je ne comprends pas pourquoi il a l'air de moins bonne qualité que celui sur le site actuel.
http://screencast.com/t/u5hXtPC2SsEM
Thomas, tu pourrais m'envoyer le favicon actuel, que je regarde si je trouve le problème ?

**Comment by ndelavergne** [comment]
Il y a vraiment un problème de qualité.
